#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 540-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 138421-web-01 100.25.194.164:80 check\n\tserver 138421-web-01 34.239.207.192:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
