#!/usr/bin/env bash
# Runs the whoami command under the user passed as argument.
sudo -u "$1" whoami#!/usr/bin/env bash
# Runs the whoami command under the user passed as argument.
sudo -u "$1" whoami
